# Generated by Django 4.2.4 on 2023-08-23 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_rename_dataset_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='author_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ads.user'),
        ),
    ]
