# Generated by Django 4.2.4 on 2023-08-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_ad_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
