# Generated by Django 4.2.4 on 2023-08-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
