# Generated by Django 4.2.4 on 2023-08-30 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_alter_user_options_alter_ad_author_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location_id',
            new_name='location',
        ),
    ]
