# Generated by Django 4.2.4 on 2023-09-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0016_alter_user_age_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('items', models.ManyToManyField(to='ads.ad')),
            ],
        ),
    ]
